export const GETLOGEEDUSERDATAREQ = "GETLOGEEDUSERDATAREQ";
export const GETLOGEEDUSERDATASUCESS = "GETLOGEEDUSERDATASUCESS";
export const GETLOGEEDUSERDATAFAILURE = "GETLOGEEDUSERDATAFAILURE";




export const PROJECTFORMPRIMAGESREQ     = "PROJECTFORMPRIMAGESREQ";
export const PROJECTFORMPRIMAGESSUCESS  = "PROJECTFORMPRIMAGESSUCESS";
export const PROJECTFORMPRIMAGESFAILURE = "PROJECTFORMPRIMAGESFAILURE";

export const UPDATEDIMAGESAWS_DATA_REQUEST = "UPDATEDIMAGESAWS_DATA_REQUEST";
export const UPDATEDIMAGESAWS_DATA_SUCESS  = "UPDATEDIMAGESAWS_DATA_SUCESS";
export const UPDATEDIMAGESAWS_DATA_FAILURE = "UPDATEDIMAGESAWS_DATA_FAILURE";


export const PROJECTCREATE_DATA_REQUEST = "PROJECTCREATE_DATA_REQUEST";
export const PROJECTCREATE_DATA_SUCESS = "PROJECTCREATE_DATA_SUCESS";
export const PROJECTCREATE_DATA_FAILURE = "PROJECTCREATE_DATA_FAILURE";
