export const LOGINUSERREQ = "LOGINUSERREQ";
export const LOGINUSERSUCESS = "LOGINUSERSUCESS";
export const LOGINUSERFAILURE = "LOGINUSERFAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ADDUSERREQ = "ADDUSERREQ";
export const ADDUSERSUCESS = "ADDUSERSUCESS";
export const ADDUSERFAILURE = "ADDUSERFAILURE";

